### ISSUE TITLE
Register your spark package

### ISSUE THREAD

**Issue by MasseGuillaume** [HyukjinKwon/spark-xml#12]
You have a dependency on Apache Spark. You can register your package at 
http://spark-packages.org/register.
It's "[a] community index of packages for Apache Spark."

**Comment by HyukjinKwon** [comment]
I did register this package, http://spark-packages.org/package/HyukjinKwon/spark-xml. This one has moved to Databricks so actually I want to unregister which looks I can't.

**Comment by HyukjinKwon** [comment]
Can you close this maybe?

**Comment by MasseGuillaume** [comment]
@HyukjinKwon You can contact Databrick to remove your package ;-)
